### ISSUE TITLE
Don't dereference aliases in endpoint params

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern-python#115]
Currently all aliases come through dereferenced in fastapi endpoints. So for the following fern definition
```yaml
PersonId: string

Person: 
  properties: 
    name: string
    age: int

endpoints:
  get: 
    path: /{personId}
    path-parameters: 
      personId: PersonId
    response: Person
```

the generated endpoint looks something like: 

```python
class AbstractPersonService: 
  
  @abc.AbstractMethod    
  get(person_id: str)-> Person
    ...
```

It would be better if the `person_id` came through as `PersonId` instead of `str`.
