### ISSUE TITLE
Generated SDK has a circular import error

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern-python#284]
The following Fern definition 

```yaml
types: 
  FieldValue:
    union:
      primitive_value: PrimitiveValue
      object_value: ObjectValue
      container_value: ContainerValue
      
  ContainerValue:
    union:
      list: list<FieldValue>
      optional: optional<FieldValue>
```

produces the error ` cannot import name 'ContainerValue' from partially initialized module `
