### ISSUE TITLE
Custom annotations for methods

### ISSUE THREAD

**Issue by estahn** [fern-api/fern-python#319]
I would like to add the following annotation to a generated methods, which effectively deal with throttling across processes and retry mechanics.

How do I best go about it?

```
@stamina.retry
@limiter.ratelimit("myratelimiter")
```

* https://pyratelimiter.readthedocs.io/en/latest/#examples
* https://stamina.hynek.me/en/stable/index.html

This could be possibly done via generator config:
```yaml
default-group: local
groups:
  local:
    generators:
      - name: fernapi/fern-python-sdk
        version: 0.3.14
        config:
            method_annotations: |
                @stamina.retry
                @limiter.ratelimit("myratelimiter")
        output:
          location: local-file-system
          path: ../test
```
