### ISSUE TITLE
Allow-multiple supersedes optional when defining request query parameters

### ISSUE THREAD

**Issue by davidkonigsberg** [fern-api/fern-python#376]
I have some query parameters for a request that look like this:

```yaml
query-parameters:
  name:
    type: optional<string>
    docs: Entity name
    allow-multiple: true
```

If I have `allow-multiple` set to false, these become optional inputs to the python function. When true, the inputs become a union of an optional string and a list of strings. 

```python
name: typing.Union[typing.Optional[str], typing.List[str]]
```

This will then complain if I don't pass 'name' into my function.

To fix this in my generated code, I updated that parameter to:
```python
name: typing.Optional[typing.Union[typing.Optional[str], typing.List[str]]] = None
```

This solved the problem for me.
