### ISSUE TITLE
[Bug] Python Generator throws if example contains optional empty value 

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern-python#426]
**Describe the bug**
When there is an example in the Fern Definition that contains an optional property, the Python Generator throws 

```
Exception: internal error: cannot generate snippet - expected an example container but found none
```

**Fern Definition To Reproduce**

```yaml
# shape.yml

service:
  endpoints:  
    doThing: 
      path: /doThing
      method: POST
      request: 
         body: optional<map<string, unknown>>
      response: string
      examples: 
        - response: "value"
```

**Expected behavior**
1) The generator should not hard fail
2) The generator should be able to generate a code snippet and ignore the optional property

**Versioning:**
 - Fern CLI: 0.15.3
 - Generator: 0.6.6
